stages:
  - docker
#  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

#build:
#  stage: build
#  image: gradle:8.5.0-jdk21  # Updated to JDK 21 version
#  script:
#    - ./gradlew clean build -x test --no-daemon
#  artifacts:
#    paths:
#      - build/libs/*.jar
#    expire_in: 1 week
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "main"'
#      when: always

docker_build_and_push:
  stage: docker
  image: docker:24.0.2
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
