spring:
  application:
    name: orders
#  datasource:
#    url: jdbc:mysql://localhost:3306/db_order
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://mysql:3306/order_db
    username: badagini
    password: BadaginiPwd123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host : rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: badagini-host

  cloud:
    stream:
      bindings:
        orderEvents-out-0:
          destination: order.events
        paymentEvents-in-0:
          destination: payment.events
      rabbit:
        bindings:
          orderEvents-out-0:
            producer:
              routing-key-expression: "'order.' + payload.status"
          paymentEvents-in-0:
            consumer:
              binding-routing-key: payment.#

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8761/service-registry/eureka/
  instance:
    prefer-ip-address: true
    hostname: orders
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}

server:
  port: 8080
  servlet:
    context-path: /orders

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true